### ISSUE TITLE
Doesn't work without CTP

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/BetterShards#100]
[20:22:11 ERROR]: Error occurred while enabling BetterShards v1.4.44 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minelink/ctplus/CombatTagPlus
        at vg.civcraft.mc.bettershards.external.CombatTagManager.<init>(CombatTagManager.java:22) ~[?:?]
        at vg.civcraft.mc.bettershards.BetterShardsPlugin.onEnable(BetterShardsPlugin.java:91) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-9797151-301db84]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-9797151-301db84]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-9797151-301db84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-9797151-301db84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:417) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:540) [spigot.jar:git-Spigot-9797151-301db84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.ClassNotFoundException: net.minelink.ctplus.CombatTagPlus
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_72-internal]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-9797151-301db84]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-9797151-301db84]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72-internal]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72-internal]
        ... 13 more

**Comment by Maxopoly** [comment]
Looking at the code this makes no sense, I'm just gonna assume I had an outdated version.
