### ISSUE TITLE
ClassCastException DisciplineGroup.execute

### ISSUE THREAD

**Issue by erocs** [Civcraft/BetterShards#102]
When running from console.

Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_10_R1.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
        at vg.civcraft.mc.namelayer.command.commands.DisciplineGroup.execute(DisciplineGroup.java:28) ~[?:?]
        at vg.civcraft.mc.namelayer.command.CommandHandler.execute(CommandHandler.java:97) ~[?:?]

**Comment by rourke750** [comment]
I think you messed up.

**Comment by Maxopoly** [comment]
Not a BetterShards issue
