### ISSUE TITLE
BetterShards SQL error

### ISSUE THREAD

**Issue by ttk2** [Civcraft/BetterShards#17]
2015-12-30 13:18:01 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB se
rver version for the right syntax to use near 'x, y, z) values ('938f1807-ba5f-4986-959e-b57724bd7e61','civ','263639c6-bad0-4f9' at line 1
2015-12-30 13:18:01 [WARN]      at sun.reflect.GeneratedConstructorAccessor202.newInstance(Unknown Source)
2015-12-30 13:18:01 [WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2015-12-30 13:18:01 [WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2015-12-30 13:18:01 [WARN]      at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2015-12-30 13:18:01 [WARN]      at com.mysql.jdbc.Util.getInstance(Util.java:382)
2015-12-30 13:18:01 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
2015-12-30 13:18:01 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
2015-12-30 13:18:01 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2015-12-30 13:18:01 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2015-12-30 13:18:01 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2015-12-30 13:18:01 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2015-12-30 13:18:01 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2015-12-30 13:18:01 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
2015-12-30 13:18:01 [WARN]      at vg.civcraft.mc.bettershards.database.DatabaseManager.addBedLocation(DatabaseManager.java:404)
2015-12-30 13:18:01 [WARN]      at vg.civcraft.mc.bettershards.listeners.BetterShardsListener.playerSleepInBed(BetterShardsListener.java:234)
2015-12-30 13:18:01 [WARN]      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-12-30 13:18:01 [WARN]      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-12-30 13:18:01 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-12-30 13:18:01 [WARN]      at java.lang.reflect.Method.invoke(Method.java:498)
2015-12-30 13:18:01 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
2015-12-30 13:18:01 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2015-12-30 13:18:01 [WARN]      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
2015-12-30 13:18:01 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.EntityHuman.a(EntityHuman.java:1155)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.EntityPlayer.a(EntityPlayer.java:566)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.BlockBed.interact(SourceFile:74)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:496)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
2015-12-30 13:18:01 [WARN]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2015-12-30 13:18:01 [WARN]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
2015-12-30 13:18:01 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
2015-12-30 13:18:01 [WARN]      at java.lang.Thread.run(Thread.java:745)

**Comment by erocs** [comment]
This is still happening.

**Comment by ProgrammerDan** [comment]
Use the latest build, rourke missed a comma.

**Comment by ProgrammerDan** [comment]
Is the issue still occurring post deploy of the fix?

**Comment by ttk2** [comment]
doesn't look like it, closing.

**Comment by ttk2** [comment]
2016-01-05 20:47:39 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB se
rver version for the right syntax to use near 'x, y, z) values ('4e62a279-7403-4572-8f93-c8206dbf5bf9','civ','263639c6-bad0-4f9' at line 1
2016-01-05 20:47:39 [WARN]      at sun.reflect.GeneratedConstructorAccessor199.newInstance(Unknown Source)
2016-01-05 20:47:39 [WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2016-01-05 20:47:39 [WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2016-01-05 20:47:39 [WARN]      at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2016-01-05 20:47:39 [WARN]      at com.mysql.jdbc.Util.getInstance(Util.java:382)
2016-01-05 20:47:39 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
2016-01-05 20:47:39 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
2016-01-05 20:47:39 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2016-01-05 20:47:39 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2016-01-05 20:47:39 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2016-01-05 20:47:39 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2016-01-05 20:47:39 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2016-01-05 20:47:39 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
2016-01-05 20:47:39 [WARN]      at vg.civcraft.mc.bettershards.database.DatabaseManager.addBedLocation(DatabaseManager.java:404)
2016-01-05 20:47:39 [WARN]      at vg.civcraft.mc.bettershards.listeners.BetterShardsListener.playerSleepInBed(BetterShardsListener.java:234)
2016-01-05 20:47:39 [WARN]      at sun.reflect.GeneratedMethodAccessor421.invoke(Unknown Source)
2016-01-05 20:47:39 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-01-05 20:47:39 [WARN]      at java.lang.reflect.Method.invoke(Method.java:498)
2016-01-05 20:47:39 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
2016-01-05 20:47:39 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2016-01-05 20:47:39 [WARN]      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
2016-01-05 20:47:39 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.EntityHuman.a(EntityHuman.java:1155)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.EntityPlayer.a(EntityPlayer.java:566)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.BlockBed.interact(SourceFile:74)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:496)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
2016-01-05 20:47:39 [WARN]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2016-01-05 20:47:39 [WARN]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
2016-01-05 20:47:39 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
2016-01-05 20:47:39 [WARN]      at java.lang.Thread.run(Thread.java:745)

nevermind.

**Comment by erocs** [comment]
9757c31dd9aeeb7fa19a9d526b430eae  BetterShards-1.3.27.jar

**Comment by ProgrammerDan** [comment]
@ttk2 I just incremented the version so it'll be clearer what is or isn't staged.

**Comment by ProgrammerDan** [comment]
See: http://build.civcraft.co/job/BetterShards-master/134/

**Comment by ttk2** [comment]
staged
