### ISSUE TITLE
[ERROR] Could not pass event AsyncPlayerPreLoginEvent to BetterShards

### ISSUE THREAD

**Issue by ttk2** [Civcraft/BetterShards#18]
2015-12-31 08:22:59 [ERROR] Could not pass event AsyncPlayerPreLoginEvent to BetterShards v1.3.24
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:248) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.LoginListener$2.run(LoginListener.java:172) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.NullPointerException
        at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106) ~[?:1.8.0_72-internal]
        at vg.civcraft.mc.bettershards.database.DatabaseManager.loadPlayerData(DatabaseManager.java:211) ~[?:?]
        at vg.civcraft.mc.bettershards.listeners.BetterShardsListener.playerPreLoginCacheInv(BetterShardsListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor189.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 6 more

**Comment by rourke750** [comment]
How often was this seen?

**Comment by ttk2** [comment]
once or twice at most.

**Comment by ProgrammerDan** [comment]
Addressed in #21
