### ISSUE TITLE
Remove previous bed if player sleeps in new bed

### ISSUE THREAD

**Issue by rourke750** [Civcraft/BetterShards#32]
https://github.com/Civcraft/BetterShards/blob/master/src/vg/civcraft/mc/bettershards/listeners/BetterShardsListener.java#L238

check if player bed exists, if it does remove from plugin and db. then call https://github.com/Civcraft/BetterShards/blob/master/src/vg/civcraft/mc/bettershards/external/MercuryManager.java#L51

**Comment by erocs** [comment]
I think you created this for this stack.

2016-01-10 12:00:56 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'UUID REMOVED' for key 'PRIMARY'
2016-01-10 12:00:56 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2016-01-10 12:00:56 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2016-01-10 12:00:56 [WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2016-01-10 12:00:56 [WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2016-01-10 12:00:56 [WARN]      at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2016-01-10 12:00:56 [WARN]      at com.mysql.jdbc.Util.getInstance(Util.java:382)
2016-01-10 12:00:56 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
2016-01-10 12:00:56 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
2016-01-10 12:00:56 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2016-01-10 12:00:56 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2016-01-10 12:00:56 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2016-01-10 12:00:56 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2016-01-10 12:00:56 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2016-01-10 12:00:56 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
2016-01-10 12:00:56 [WARN]      at vg.civcraft.mc.bettershards.database.DatabaseManager.addBedLocation(DatabaseManager.java:405)
2016-01-10 12:00:56 [WARN]      at vg.civcraft.mc.bettershards.listeners.BetterShardsListener.playerSleepInBed(BetterShardsListener.java:239)

**Comment by rourke750** [comment]
https://github.com/Civcraft/BetterShards/commit/4013cb111d476e7058ccb5dc4d0d25c5634e2adb
