### ISSUE TITLE
Failed to load player data, can not pass playerjoinevent. 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/BetterShards#48]
2016-02-12 17:19:55 [INFO] [BetterShards] Load for 8326bc56-1ed9-40ff-8f24-46bf3e300e51
2016-02-12 17:19:55 [ERROR] [BetterShards] Failed to load player data for ttk2
2016-02-12 17:19:55 [INFO] [BetterShards] No player data found for ttk2
2016-02-12 17:19:55 [ERROR] Could not pass event PlayerJoinEvent to BetterShards v1.3.50
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.bettershards.misc.RandomSpawn.getLocation(RandomSpawn.java:101) ~[?:?]
        at vg.civcraft.mc.bettershards.misc.RandomSpawn.getLocation(RandomSpawn.java:96) ~[?:?]
        at vg.civcraft.mc.bettershards.misc.RandomSpawn.handleFirstJoin(RandomSpawn.java:64) ~[?:?]
        at vg.civcraft.mc.bettershards.listeners.BetterShardsListener.playerJoinEvent(BetterShardsListener.java:96) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-880a532]
        ... 14 more

**Comment by Maxopoly** [comment]
This was caused by BetterShards not being configured, this is fixed for us and not an actual issue.
