### ISSUE TITLE
PlayerStillDeadException

### ISSUE THREAD

**Issue by erocs** [Civcraft/BetterShards#84]
[02:04:06 WARN](vg.civcraft.mc.bettershards.misc.PlayerStillDeadException):        at vg.civcraft.mc.bettershards.BetterShardsPlugin.teleportPlayerToServer(BetterShardsPlugin.java:212)
[02:04:06 WARN](vg.civcraft.mc.bettershards.misc.PlayerStillDeadException):        at vg.civcraft.mc.bettershards.BetterShardsAPI.connectPlayer(BetterShardsAPI.java:36)
[02:04:06 WARN](vg.civcraft.mc.bettershards.misc.PlayerStillDeadException):        at vg.civcraft.mc.bettershards.misc.RandomSpawn.handleDeath(RandomSpawn.java:83)
[02:04:06 WARN](vg.civcraft.mc.bettershards.misc.PlayerStillDeadException):        at vg.civcraft.mc.bettershards.listeners.BetterShardsListener$2.run(BetterShardsListener.java:254)
[02:04:06 WARN](vg.civcraft.mc.bettershards.misc.PlayerStillDeadException):        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[02:04:06 WARN](vg.civcraft.mc.bettershards.misc.PlayerStillDeadException):        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[02:04:06 WARN](vg.civcraft.mc.bettershards.misc.PlayerStillDeadException):        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741)
[02:04:06 WARN](vg.civcraft.mc.bettershards.misc.PlayerStillDeadException):        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
[02:04:06 WARN](vg.civcraft.mc.bettershards.misc.PlayerStillDeadException):        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
[02:04:06 WARN](vg.civcraft.mc.bettershards.misc.PlayerStillDeadException):        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)

**Comment by Maxopoly** [comment]
Almost everything changed since this issue was made and we havent seens omething like this in ages, so let's assume it's fixed
