### ISSUE TITLE
Every few seconds on Bungee, concurrent modification problem

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/BetterShards#88]
```
02:39:40 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@2b30a42c, id=9, owner=vg.civcraft.mc.bettershards.bungee.BetterShard
sBungee@1b45c0e, task=vg.civcraft.mc.bettershards.bungee.ServerHandler$1@75d2da2d, delay=10000, period=10000, running=true) encountered an exception
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.remove(HashMap.java:1443)
    at vg.civcraft.mc.bettershards.bungee.ServerHandler$1.run(ServerHandler.java:68)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ProgrammerDan** [comment]
Should be fixed by @BlackXnt 's PR.

**Comment by rbp15** [comment]
Was it verified as fixed prior to closing?

**Comment by ProgrammerDan** [comment]
The code that caused this error no longer exists.

**Comment by rbp15** [comment]
Awesome - saw the "should be" fixed... QA gene turned on. :)

**Comment by ProgrammerDan** [comment]
:D Valid QQ!
